site_name: Anodet Anvil Documentation

theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true


nav:
  - Overview: index.md
  - Run: run.md
  - Anodet: ano.md


